#!/bin/bash

# Ensure the script is run with sudo for lshw and ufw commands to work fully\
if [ "$EUID" -ne 0 ]; then
  echo "Please run as root (e.g., sudo ./system_report.sh)"
  exit 1
fi

# Determine the actual user who invoked sudo\
CURRENT_USER=$\{SUDO_USER:-$USER\}
CURRENT_DATE=$(date +"%A, %b %d, %Y %T %Z")
HOST=$(hostname)

# Header\
echo "System Report for $HOST generated by $CURRENT_USER, on $CURRENT_DATE"
echo ""

# System Information Section\
echo "System Information"
echo "------------------"

# OS: Source os-release and extract the PRETTY_NAME variable\
source=/etc/os-release
echo "OS: $PRETTY_NAME"

# Uptime: Strip the extra info using sed\
UPTIME_VAL=$(uptime -p 2>/dev/null || uptime | sed -E 's/^[^,]*up *//; s/, *[[:digit:]]* user.*//')
echo "Uptime: $UPTIME_VAL"

# CPU: Extract the product line from lshw\
CPU=$(sudo lshw -class processor 2>/dev/null | grep -m 1 "product:" | sed 's/^[ \\t]*product: //')
echo "CPU: $CPU"

# RAM: Extract total memory from free\
RAM=$(free -h | awk '/^Mem:/ \{print $2\}')
echo "RAM: $RAM"

# Disk(s): Extract product and size from lshw and format them on one line\
DISKS=$(sudo lshw -class disk 2>/dev/null | awk '/product:/ \{p=$0; sub(/.*product: /, "", p)\} /size:/ \{s=$0; sub(/.*size: /, "", s); print p " (" s ")"\}' | paste -sd ", ")
echo "Disk(s): $\{DISKS:-None detected\}"

# Video: Extract the display product from lshw\
VIDEO=$(sudo lshw -class display 2>/dev/null | grep -m 1 "product:" | sed 's/^[ \\t]*product: //')
echo "Video: $\{VIDEO:-None detected\}"

# Networking: Find default gateway interface, then get IPs\
DEFAULT_IF=$(ip r | awk '/default/ \{print $5\}' | head -n 1)
HOST_IP=$(ip a show dev "$DEFAULT_IF" 2>/dev/null | awk '/inet / \{print $2\}' | cut -d/ -f1 | head -n 1)
GATEWAY_IP=$(ip r | awk '/default/ \{print $3\}' | head -n 1)
echo "Host Address: $\{HOST_IP:-Unknown\}"
echo "Gateway IP: $\{GATEWAY_IP:-Unknown\}"

# DNS Server: Extract nameservers from resolv.conf\
DNS=$(grep "nameserver" /etc/resolv.conf | awk '\{print $2\}' | paste -sd ", ")
echo "DNS Server: $\{DNS:-Unknown\}"

echo ""

# System Status Section\
echo "System Status"
echo "-------------"

# Users Logged In: Parse 'who' unique the list, and separate with commas\
USERS=$(who | awk '\{print $1\}' | sort -u | paste -sd ",")
echo "Users Logged In: $\{USERS:-None\}"

# Disk Space: Find local filesystems (/dev/...), print mount point ($6) and free space ($4)\
DISK_SPACE=$(df -h | awk '$1 ~ /^\\/dev\\// \{print $6, $4\}' | paste -sd ", ")
echo "Disk Space: $DISK_SPACE"

# Process Count: Count lines from ps\
PROC_COUNT=$(ps -e --no-headers | wc -l)
echo "Process Count: $PROC_COUNT"

# Load Averages: Parse uptime output\
LOAD_AVG=$(uptime | awk -F'load average:' '\{print $2\}' | sed 's/^[ \\t]*//')
echo "Load Averages: $LOAD_AVG"

# Listening Network Ports: Parse ss, extract port numbers, sort unique, comma separate\
PORTS=$(ss -tuln | awk 'NR>1 \{print $5\}' | rev | cut -d: -f1 | rev | sort -nu | paste -sd ", ")
echo "Listening Network Ports: $PORTS"

# UFW Status: Extract active/inactive status from ufw\
UFW_STAT=$(sudo ufw status 2>/dev/null | grep -i "Status:" | awk '\{print $2\}')
echo "UFW Status: $\{UFW_STAT:-Not Installed\}"
echo ""}
