#!/bin/bash

# Need to run in sudo
if [ "$EUID" -ne 0 ]; then
  echo "Please run this script with sudo."
  exit 1
fi

# 1. System Report 
HOSTNAME=$(hostname)
USERNAME=${SUDO_USER:-$USER}
DATETIME=$(date "+%Y-%m-%d %H:%M:%S")

echo "System Report for $HOSTNAME generated by $USERNAME, on $DATETIME"
echo ""

# 2. System Information Section
echo "System Information"
echo "------------------"

# OS Name and Version
source /etc/os-release
echo "OS: $NAME $VERSION"

# Uptime
echo "Uptime: $(uptime -p 2>/dev/null || uptime | awk -F'( |,|:)+' '{print $6 " hours, " $7 " minutes"}')"

# CPU Processor Make and Model 
CPU=$(sudo lshw -class processor 2>/dev/null | awk -F'product: ' '/product:/ {print $2; exit}')
echo "CPU: ${CPU:-Not Found}"

# RAM Installed Size
RAM=$(free -h | awk '/^Mem:/ {print $2}')
echo "RAM: $RAM"

# Disk Make, Model, and Size
DISKS=$(sudo lshw -class disk 2>/dev/null | awk -F'product: |size: ' '/product:/ {prod=$2} /size:/ {print prod " " $2}' | paste -sd ', ' -)
echo "Disk(s): $DISKS"

# Video Card Make and Model 
VIDEO=$(sudo lshw -class display 2>/dev/null | awk -F'product: ' '/product:/ {print $2; exit}')
echo "Video: ${VIDEO:-Not Found}"

# Network Configurations
GATEWAY_IP=$(ip r | awk '/default/ {print $3}')
DEFAULT_INT=$(ip r | awk '/default/ {print $5}')
HOST_ADDRESS=$(ip a show dev "$DEFAULT_INT" 2>/dev/null | awk '/inet / {print $2}' | cut -d/ -f1)

# DNS Server
DNS_SERVER=$(awk '/^nameserver/ {print $2}' /etc/resolv.conf | paste -sd ', ' -)

echo "Host Address: $HOST_ADDRESS"
echo "Gateway IP: $GATEWAY_IP"
echo "DNS Server: $DNS_SERVER"
echo ""

# 3. System Status Section
echo "System Status"
echo "-------------"

# Logged In Users
USERS=$(who | awk '{print $1}' | sort -u | paste -sd ',' -)
echo "Users Logged In: $USERS"

# Free Disk Space (/mountpoint N)
DISK_SPACE=$(df -h | awk '/^\/dev\// {print $6 " " $4}' | paste -sd ', ' -)
echo "Disk Space: $DISK_SPACE"

# Process Count
PROCESS_COUNT=$(ps -e --no-headers | wc -l)
echo "Process Count: $PROCESS_COUNT"

# Load Averages
LOAD_AVGS=$(uptime | awk -F'load average: ' '{print $2}')
echo "Load Averages: $LOAD_AVGS"

# Listening Network Ports
PORTS=$(ss -tuln | awk 'NR>1 {print $5}' | awk -F: '{print $NF}' | sort -nu | paste -sd ', ' -)
echo "Listening Network Ports: $PORTS"

# UFW Status
UFW_STATUS=$(sudo ufw status 2>/dev/null | awk '/Status:/ {print $2}')
echo "UFW Status: ${UFW_STATUS:-inactive}"
